### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by getkey** [whitequark/murmurhash3-js#2]
Hey, can you publish this to NPM? :-)

**Comment by whitequark** [comment]
There's a bunch already. https://www.npmjs.com/package/murmurhash-js ?

**Comment by getkey** [comment]
True, but I know you write good code.

But I'll go with the one you linked, @mikolalysenko is a clever guy too.

**Comment by whitequark** [comment]
From a quick look these are basically equivalent.
